# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNS-IgnoreVerisign
version:      0.01
version_from: lib/Net/DNS/IgnoreVerisign.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    Net::DNS:                      0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
